### ISSUE TITLE
_tpl_discussion() and _tpl_userpage() should return instead of echo

### ISSUE THREAD

**Issue by mightymt** [selfthinker/dokuwiki_template_starter#9]
I was recently building my own template based on the starter template and noticed a problem with the functions ```_tpl_discussion()``` and ```_tpl_userpage()```. 
E.g. for the user tools there is the following code (```main.php``` starting at line 76):

```php 
<?php _tpl_toolsevent('usertools', array(
  'admin' => tpl_action('admin', 1, 'li', 1),
  'userpage' => _tpl_action('userpage', 1, 'li', 1),
  'profile' => tpl_action('profile', 1, 'li', 1),
  'register' => tpl_action('register', 1, 'li', 1),
  'login' => tpl_action('login', 1, 'li', 1),
)); ?>
```
Now (if userpage is enabled in the config) this will display the link for the **user page first** and afterwards the ones for the admin, profile page and so on. However if you look at the code above one would expect the link for the **admin page** to be displayed **first**.

The reason is, that the functions ```_tpl_discussion()``` and ```_tpl_userpage()``` **echo** their output while the core function ```tpl_action()``` **returns** it.

I think that the code should be changed so that ```_tpl_discussion()``` and ```_tpl_userpage()``` (and subsequently ```_tpl_action()```) also **return** instead of echo.

**Comment by selfthinker** [comment]
This cannot be changed without some core changes as well. Both `_tpl_discussion()` and `_tpl_userpage()` are using the core's `tpl_pagelink()` which unfortunately always echos.

**Comment by selfthinker** [comment]
I fixed this now, but it's not ideal. The best solution would be to move this functionality out of the template anyway (as mentioned in #7).
